import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NextAuthProvider from "@/lib/auth/provider";
import Header from "./components/common/Header";
import { Suspense } from "react";
import Loading from "./components/common/Loading";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      ><NextAuthProvider>
      <Header />
      <Suspense fallback={<Loading />}>
        {children}
      </Suspense>
    </NextAuthProvider>
      </body>
    </html>
  );
}
